
create table dim_agencia(
    dim_agencia_id int not null auto_increment primary key, 
    agencia_id int,
    agencia_codigo varchar(200),
    agencia_nombre varchar(200),
    agencia_ubicacion varchar(200),
    agencia_departamento varchar(100),
    agencia_provincia varchar(100),
    agencia_distrito varchar(100)
); 

create table dim_empleado(
    dim_empleado_id int not null auto_increment primary key,
    agencia_id int,
    agencia_codigo varchar(200),
    agencia_nombre varchar(200),
    agencia_ubicacion varchar(200),
    agencia_departamento varchar(100),
    agencia_provincia varchar(100),
    agencia_distrito varchar(100),
    empleado_id int,
    empleado_nombre varchar(200),
    empleado_fecha_nacimiento Date,
    empleado_cargo varchar(200) 
); 


create table dim_cliente(
    dim_cliente_id int not null auto_increment primary key,
    cliente_id int,
    cuenta_id int,
    cliente_aval varchar(200),
    cliente_estado varchar(200),
    cliente_tipo varchar(200),
    cliente_labora_empresa_id int,

    cliente_labora_email varchar(100),
    cliente_labora_ruc varchar(100),
    cliente_labora_razon_social varchar(100),
    cliente_labora_nombre_comercial varchar(100),
    cliente_labora_tipo varchar(100),
    cliente_labora_giro_negocio varchar(100),
    cliente_labora_cargo_laboral varchar(100),

    cliente_empresa_id int,
    cliente_empresa_razon_social varchar(100),
    cliente_empresa_nombre_comercial varchar(100),
    cliente_empresa_giro_negocio varchar(100),
    cliente_tipo_empresa varchar(100),

    persona_id int,
    cliente_nombre varchar(100),
    cliente_email varchar(100),
    cliente_fecha_nacimiento Date,
    cliente_sexo varchar(100),
    cliente_edad varchar(100),
    cliente_tipo_vivienda varchar(100),
    cliente_estado_civil varchar(100),
    cliente_tipo_ingreso varchar(100),
    cliente_nivel_estudios varchar(100),
    cliente_sector_economico varchar(100),
    cliente_profesion varchar(100),
    cliente_ocupacion varchar(100),
    cliente_num_dependientes varchar(100),
    cliente_num_hijos varchar(100),
    cliente_num_anios_envivienda varchar(100),
    cliente_monto_devengado varchar(100),
    cliente_fecha_creacion Date, 
    agencia_id int,
    agencia_codigo varchar(200),
    agencia_nombre varchar(200),
    agencia_ubicacion varchar(200),
    agencia_departamento varchar(100),
    agencia_provincia varchar(100),
    agencia_distrito varchar(100),
    empleado_id int,
    empleado_renuncia varchar(200),
    empleado_promotor varchar(200)
); 


create table dim_cliente_empresa(
    dim_cliente_empresa_id int not null auto_increment primary key,
    empresa_id int,
    cliente_empresa_email varchar(200),
    cliente_empresa_ruc varchar(200),
    cliente_empresa_razon_social varchar(200),
    cliente_empresa_nombre_comercial varchar(200),
    cliente_empresa_tipo varchar(200),
    cliente_empresa_giro_negocio varchar(200),
    cliente_id int,
    cliente_aval varchar(200),
    cliente_estado varchar(200),
    cliente_tipo varchar(200), 
    agencia_id int,
    agencia_codigo varchar(200),
    agencia_nombre varchar(200),
    agencia_ubicacion varchar(200),
    agencia_departamento varchar(100),
    agencia_provincia varchar(100),
    agencia_distrito varchar(100),
    empleado_id int,
    empleado_renuncio varchar(200),
    empleado_promotor varchar(200)
); 


create table dim_producto_credito(
    dim_producto_credito_id int not null auto_increment primary key,
    cuenta_id int,
    cuenta_producto varchar(200),
    cuenta_tipo_producto varchar(200),
    cuenta_tipo_credito varchar(200),
    cuenta_moneda varchar(200),
    cuenta_fecha_desembolso Date,
    cuenta_fecha_ini_pago Date,
    cuenta_fecha_fin_pago Date,
    cuenta_fecha_fin_real Date,
    cuenta_tipo_calculo_cuota varchar(200),
    cuenta_modalidad_pago varchar(200),
    cuenta_dia_pago varchar(200),
    cuenta_nro_cuotas int,
    cuenta_periodo int,
    cuenta_encaje decimal(12,4),
    cuenta_monto_desembolso decimal(12,4),
    cuenta_capital decimal(12,4),
    cuenta_monto_total decimal(12,4),
    cuenta_monto_actual decimal(12,4),
    cuenta_interes decimal(12,4),
    cuenta_tea decimal(12,4),
    cuenta_tem decimal(12,4),
    cuenta_ted decimal(12,4),
    cuenta_tea_mora decimal(12,4),
    cuenta_tem_mora decimal(12,4),
    cuenta_ted_mora decimal(12,4),
    cuenta_cuota_simple varchar(200),
    cuenta_cuota_doble varchar(200),
    cuenta_tiene_cuota_doble varchar(200),
    cuenta_es_pronto_pago varchar(200),
    cuenta_periodo_gracia varchar(200),
    cuenta_interes_periodo_gracia varchar(200),
    cuenta_capital_condonado decimal(12,4),
    cuenta_interes_condonado decimal(12,4),
    cliente_id int,
    cliente_empresa_id int,
    cliente_aval varchar(200),
    cliente_estado varchar(200),
    cliente_tipo varchar(200),
    agencia_id int,
    agencia_codigo varchar(200),
    agencia_nombre varchar(200),
    agencia_ubicacion varchar(200),
    agencia_departamento varchar(200),
    agencia_provincia varchar(200),
    agencia_distrito varchar(200),
    empleado_id int,
    empleado_analita_id int,
    empleado_promotor varchar(200),
    empleado_analista varchar(200)
); 
 
create table dim_tiempo(
    dim_tiempo_id int not null auto_increment primary key,
    cuenta_id int,
    fecha varchar(20),
    anio varchar(20),
    mes varchar(20),
    dia varchar(20)
); 

create table fact_credito_otorgado(
    fact_credito_otorgado_id int not null auto_increment primary key,
    dim_agencia_id int,
    dim_empleado_id int,
    dim_tiempo_id int,
    dim_cliente_id int,
    dim_cliente_empresa_id int,
    dim_producto_credito_id int,
    empleado_agencia_id int,
    cliente_id int,
    cuenta_id int,
    cuenta_fecha_desembolso Date,
    cuenta_anio_desembolso varchar(4),
    cuenta_mes_desembolso varchar(2),
    cuenta_dia_desembolso varchar(2),
    cuenta_monto_desembolso varchar(100),
    cuenta_capital varchar(100),
    cuenta_monto_total varchar(100),
    cuenta_monto_actual varchar(100),
    cuenta_nro_cuotas varchar(100),
    cuenta_periodo varchar(100),
    cuenta_modalidad_pago varchar(100),
    cuenta_tea varchar(100),
    cuenta_tea_mora varchar(100),
    FOREIGN KEY (dim_agencia_id) REFERENCES dim_agencia (dim_agencia_id) ,
    FOREIGN KEY (dim_empleado_id) REFERENCES dim_empleado (dim_empleado_id) ,
    FOREIGN KEY (dim_tiempo_id) REFERENCES dim_tiempo (dim_tiempo_id) , -- fechas de desembolso
    FOREIGN KEY (dim_cliente_id) REFERENCES dim_cliente (dim_cliente_id) ,
    FOREIGN KEY (dim_cliente_empresa_id) REFERENCES dim_cliente_empresa (dim_cliente_empresa_id) ,
    FOREIGN KEY (dim_producto_credito_id) REFERENCES dim_producto_credito (dim_producto_credito_id) ,
    FOREIGN KEY (dim_agencia_id) REFERENCES dim_agencia (dim_agencia_id)  -- agencia en donde labora el empleado
); 